### ISSUE TITLE
Non-integer Polarity

### ISSUE THREAD

**Issue by phobson** [pygridgen/holo-gridgen#3]
The polarity of a boundary isn't limited to -1, 0, 1. 

It can be any real number, not just integers, as shown in the second example here:
https://pygridgen.readthedocs.io/en/latest/tutorial/gridgen_examples.html#These-are-just-weird

Data for that example:
https://github.com/pygridgen/pygridgen/blob/master/docs/tutorial/gg_examples/xy.4

...which is minimally modified from Dr. Sakov's original gridgen-c examples to include a more clear ul_idx indicator column:
https://github.com/sakov/gridgen-c/blob/master/gridgen/examples/xy.4

For now, it I think it makes sense to leave the UI as-is and make the possible polarity values  `{-1, 0, 1}`. But I wanted to get e.g., @hetland 's take on how often non-integer polarities are used. I've never needed them in my river & estuary work. My suspicion is that it's mathematically interesting, but not very practical.

**Comment by hetland** [comment]
So, I didn't even realize that this was an option! 

I think I would never do this because I try very hard to make the most orthogonal grid possible, and those choices bend orthogonality a bit too much for my tastes. So I agree: mathematically interesting, but not practical. Therefore I also agree that it should not be an exposed part of the GUI.

**Comment by jlstevens** [comment]
Thanks for raising this possibility.

Looking at the code, it should be very easy to assign different values to the three node types (positive, neutral and negative). In fact it may already be possible to use non-integer polarity as long as the condition for mesh generation remains (that the sum along the boundary needs to be four before a mesh can be generated).

To be certain, I'll test with the examples you've linked to above and include such an example in the documentation notebook.

**Comment by jlstevens** [comment]
It can already be made to work for an example like in [xy.4](https://github.com/pygridgen/pygridgen/blob/master/docs/tutorial/gg_examples/xy.4) without any changes to the code. Here a beta value of `1.33333333` (4/3) means you only need three positive nodes before you can generate a mesh:

<img width=400 src="https://user-images.githubusercontent.com/890576/95988740-f6449780-0dee-11eb-943d-8371afd140e8.png"></img>

All I will change for now is to make `_polarity_value` into a documented, public parameter to indicate that it can be changed (with a corresponding example in the docs).

**Comment by hetland** [comment]
I think this is nice, and I think this is the right level of exposure of that feature. I.e., accessible, but not an option in the GUI.

**Comment by jlstevens** [comment]
Pushed in commit 5f4926 in https://github.com/pygridgen/holo-gridgen/pull/2:

![image](https://user-images.githubusercontent.com/890576/95991407-5852cc00-0df2-11eb-8395-86ac4d86cc6c.png)

**Comment by phobson** [comment]
Very cool! I agree this is sufficiently exposed.
