### ISSUE TITLE
Rename repo to hologridgen and PyPI package

### ISSUE THREAD

**Issue by jlstevens** [pygridgen/holo-gridgen#4]
The name holo-gridgen is unfortunately not one Python can use to import.

For this reason, I've renamed the project to `hologrid` as that name was available on PyPI (which I've now [snapped up](https://pypi.org/project/hologrid/)). The main goal here is to register the name into the python ecosystem and the next step will be to make a conda package. The changes I've made are in https://github.com/pygridgen/holo-gridgen/pull/2 and note that I'm working on getting the PyPI README rendering correctly (the GIFs won't appear till https://github.com/pygridgen/holo-gridgen/pull/2 is merged).

@rsignell-usgs It looks like you initialized this repo: could you rename it to `hologrid` given that I don't have admin access?

Packaging for conda will be quick and easy as soon as the new development build for HoloViews is available. Here are the steps we would need to make `hologrid` pip installable:

- [ ] `pygridgen` would need to be pip installable. I don't know how much work that would be, especially given the typical difficulty of working with the dependencies in the geostack.
- [ ] New releases of HoloViews and GeoViews would need to make it onto PyPI.

I realize that being conda installable is the priority, but it would be nice to have `hologrid` installable from PYPI if it isn't too much trouble.

**Comment by rsignell-usgs** [comment]
I'm happy to rename, but @hetland and @phobson , what do you think would be the best name?
* hologrid
* hologridgen
* hgridgen
* cgridgen
* yagridgen (yet another gridgen)
* <other?>

**Comment by hetland** [comment]
I like 'hologrid' the best, but also think that 'gridgen' should be in the name to reference the original, underlying package.

Given that, my vote is 'hologridgen'.

**Comment by jlstevens** [comment]
@rsignell-usgs Do you concur with 'hologridgen'? I'm happy to adopt any importable name as long as there is a consensus! 

Any opinion @phobson?

**Comment by phobson** [comment]
I think hologridgen is the best.

**Comment by jlstevens** [comment]
In that case I'm happy to update the packaging definitions (and build a new conda package) once @rsignell-usgs gets rid of the dash in the repo name (assuming we do now have a consensus!). At that point, I will also register the name with PyPI.

**Comment by rsignell-usgs** [comment]
Thanks for the reminder @jlstevens!  Renamed!

**Comment by jlstevens** [comment]
Thanks!

**Comment by rsignell-usgs** [comment]
@jlstevens or @jbednar, can you please make a source distribution release on PyPI (see only wheels)?
 
Or tag a release on GitHub?  

This will help @ocefpaf release hologridgen on conda-forge.

**Comment by jlstevens** [comment]
I can update the package on PyPI to have sdist but it doesn't look like pygridgen is pip installable. This means hologridgen won't be pip installable either but I suppose the idea here is to simply specify a conda source for the conda-forge recipe?

**Comment by jlstevens** [comment]
I've uploaded the sdist which you can download from here: https://pypi.org/project/hologridgen/#files

I bumped the version to 1.0.2 due to the project renaming.

Hope that helps!

**Comment by ocefpaf** [comment]
Thanks. Adding it in https://github.com/conda-forge/staged-recipes/pull/13271

**Comment by jlstevens** [comment]
I see the PR on staged recipes has been merged and there is now a [feedstock](https://github.com/conda-forge/hologridgen-feedstock)

I tried `conda install -c conda-forge hologridgen` and it does install though solving does take a while (and without setting strict channel priority it took so long that I gave up).

I'll now test that this works at which point I'll update the README.

**Comment by jlstevens** [comment]
All seems to be working! :-)

**Comment by ocefpaf** [comment]
With micromamba this took 15s for me:

```
micromamba create --name TMP python=3.8 hologridgen --channel conda-forge --strict-channel-priority --yes
```
