### ISSUE TITLE
How to delete a point?

### ISSUE THREAD

**Issue by rsignell-usgs** [pygridgen/holo-gridgen#7]
I added a point by mistake and can't figure out how to remove it.  
![2020-12-16_7-46-14](https://user-images.githubusercontent.com/1872600/102350784-731cfa80-3f73-11eb-872f-bd2a940088b7.jpg)

**Comment by jbednar** [comment]
Select it, then press Backspace or Delete on the keyboard?

**Comment by rsignell-usgs** [comment]
Ah.  Thanks @jbednar !

The procedure (thanks to Jim's tip and trial and error):
1. select the "Point Draw Tool"
2. click on the point you want to delete
3. click the "backspace" key on your keyboard (at least on a Windows PC, perhaps "delete" on other machines?)
![2020-12-16_14-21-44](https://user-images.githubusercontent.com/1872600/102396476-7da6b680-3faa-11eb-8992-e09bd2050551.jpg)

**Comment by jbednar** [comment]
Right; it's Delete on a Mac.
