### ISSUE TITLE
Is it important to use python=3.7?

### ISSUE THREAD

**Issue by rsignell-usgs** [pygridgen/holo-gridgen#8]
I didn't see the mention of python=3.7 until after I created the "hologridgen" environment thusly:
```
conda create -n hologridgen hologridgen ipykernel
```
which installs python=3.8.   Seems to work fine, but is there a reason to stick with python=3.7?

**Comment by jbednar** [comment]
I believe it's just that we developed and tested on 3.7; the 3.8 ecosystem should be mature enough to use by now. 3.9 probably won't work yet.
